name: test

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # github personal access token necessary
      - name: Test
        run: |
          echo "joe"
          echo ${GITHUB_REF_NAME}
          echo  ${GITHUB_REF}
          echo  ${GITHUB_BASE_REF}
          echo ${{github.event.head_commit}}
          echo ${{github.event}}
      - name: push to staging
        run: |
          git push origin ${GITHUB_REF_NAME}:staging
      # - name: Switch to staging
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.GH_PAT }} # github personal access token necessary
      #     ref: staging
      #     fetch-depth: 0
      # - name: Rebase and push develop to staging
      #   run: |
      #     echo "Commit is a tagged release"
      #     git fetch
      #     git pull origin main --rebase
      #     git push --tags && git push --force
