name: test

on:
  push:
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # github personal access token necessary
      - name: Test
        run: |
          echo "joe"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "GITHUB_REF:  ${GITHUB_REF}"
          echo "GITHUB_BASE_REF:  ${GITHUB_BASE_REF}"
          echo "github.event.head_commi.id: "${{github.event.head_commit.id}}"
          echo "github.event.head_commit.tree_id: ${{github.event.head_commit.tree_id}}"
          echo "github.event.base_ref: ${{github.event.base_ref}}"
          echo "github.event.ref: ${{github.event.ref}}"
          echo "github.ref_type: ${{github.ref_type}}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
      - name: Set env
        run: echo "GITHUB_TAG=$(git describe --tag $GITHUB_SHA)" >> $GITHUB_ENV
      - name: echo env
        run: echo $GITHUB_TAG
      - name: push to staging
        run: |
          git push origin ${GITHUB_REF_NAME}:staging
      # - name: Switch to staging
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.GH_PAT }} # github personal access token necessary
      #     ref: staging
      #     fetch-depth: 0
      # - name: Rebase and push develop to staging
      #   run: |
      #     echo "Commit is a tagged release"
      #     git fetch
      #     git pull origin main --rebase
      #     git push --tags && git push --force
