name: Deploy to S3

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "joe"
          echo ${GITHUB_REF_NAME}
          echo  ${GITHUB_REF}
          echo  ${GITHUB_BASE_REF}
      - name: Switch to staging
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # github personal access token necessary
          ref: staging
          fetch-depth: 0
      - name: Rebase and push develop to staging
        run: |
          echo "Commit is a tagged release"
          git fetch
          git pull origin main --rebase
          git push --tags && git push --force
